# Supabase CLI Project Configuration
project_id = "tellnest"

[functions.content-moderation]
verify_jwt = false

[functions.clerk-webhook]
verify_jwt = false

[functions.aggregate-analytics]
verify_jwt = false
