/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as FollowingRouteImport } from './routes/following'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SecretAdminpanelRouteImport } from './routes/secret-adminpanel'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AuthorAuthorIdRouteImport } from './routes/author.$authorId'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as GenreSlugRouteImport } from './routes/genre.$slug'
import { Route as WorksWorkIdRouteImport } from './routes/works.$workId'
import { Route as WriteIndexRouteImport } from './routes/write.index'
import { Route as WriteNewRouteImport } from './routes/write.new'
import { Route as ReadWorkIdChapterIdRouteImport } from './routes/read.$workId.$chapterId'
import { Route as WriteAnalyticsWorkIdRouteImport } from './routes/write.analytics.$workId'
import { Route as WriteManageWorkIdRouteImport } from './routes/write.manage.$workId'
import { Route as WriteEditorWorkIdChapterIdRouteImport } from './routes/write.editor.$workId.$chapterId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowingRoute = FollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretAdminpanelRoute = SecretAdminpanelRouteImport.update({
  id: '/secret-adminpanel',
  path: '/secret-adminpanel',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorAuthorIdRoute = AuthorAuthorIdRouteImport.update({
  id: '/author/$authorId',
  path: '/author/$authorId',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GenreSlugRoute = GenreSlugRouteImport.update({
  id: '/genre/$slug',
  path: '/genre/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksWorkIdRoute = WorksWorkIdRouteImport.update({
  id: '/works/$workId',
  path: '/works/$workId',
  getParentRoute: () => rootRouteImport,
} as any)
const WriteIndexRoute = WriteIndexRouteImport.update({
  id: '/write/',
  path: '/write/',
  getParentRoute: () => rootRouteImport,
} as any)
const WriteNewRoute = WriteNewRouteImport.update({
  id: '/write/new',
  path: '/write/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadWorkIdChapterIdRoute = ReadWorkIdChapterIdRouteImport.update({
  id: '/read/$workId/$chapterId',
  path: '/read/$workId/$chapterId',
  getParentRoute: () => rootRouteImport,
} as any)
const WriteAnalyticsWorkIdRoute = WriteAnalyticsWorkIdRouteImport.update({
  id: '/write/analytics/$workId',
  path: '/write/analytics/$workId',
  getParentRoute: () => rootRouteImport,
} as any)
const WriteManageWorkIdRoute = WriteManageWorkIdRouteImport.update({
  id: '/write/manage/$workId',
  path: '/write/manage/$workId',
  getParentRoute: () => rootRouteImport,
} as any)
const WriteEditorWorkIdChapterIdRoute =
  WriteEditorWorkIdChapterIdRouteImport.update({
    id: '/write/editor/$workId/$chapterId',
    path: '/write/editor/$workId/$chapterId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRoute
  '/discover': typeof DiscoverRoute
  '/following': typeof FollowingRoute
  '/library': typeof LibraryRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/secret-adminpanel': typeof SecretAdminpanelRoute
  '/settings': typeof SettingsRoute
  '/author/$authorId': typeof AuthorAuthorIdRoute
  '/category/$slug': typeof CategorySlugRoute
  '/genre/$slug': typeof GenreSlugRoute
  '/works/$workId': typeof WorksWorkIdRoute
  '/write/new': typeof WriteNewRoute
  '/write/': typeof WriteIndexRoute
  '/read/$workId/$chapterId': typeof ReadWorkIdChapterIdRoute
  '/write/analytics/$workId': typeof WriteAnalyticsWorkIdRoute
  '/write/manage/$workId': typeof WriteManageWorkIdRoute
  '/write/editor/$workId/$chapterId': typeof WriteEditorWorkIdChapterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRoute
  '/discover': typeof DiscoverRoute
  '/following': typeof FollowingRoute
  '/library': typeof LibraryRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/secret-adminpanel': typeof SecretAdminpanelRoute
  '/settings': typeof SettingsRoute
  '/author/$authorId': typeof AuthorAuthorIdRoute
  '/category/$slug': typeof CategorySlugRoute
  '/genre/$slug': typeof GenreSlugRoute
  '/works/$workId': typeof WorksWorkIdRoute
  '/write/new': typeof WriteNewRoute
  '/write': typeof WriteIndexRoute
  '/read/$workId/$chapterId': typeof ReadWorkIdChapterIdRoute
  '/write/analytics/$workId': typeof WriteAnalyticsWorkIdRoute
  '/write/manage/$workId': typeof WriteManageWorkIdRoute
  '/write/editor/$workId/$chapterId': typeof WriteEditorWorkIdChapterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRoute
  '/discover': typeof DiscoverRoute
  '/following': typeof FollowingRoute
  '/library': typeof LibraryRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/secret-adminpanel': typeof SecretAdminpanelRoute
  '/settings': typeof SettingsRoute
  '/author/$authorId': typeof AuthorAuthorIdRoute
  '/category/$slug': typeof CategorySlugRoute
  '/genre/$slug': typeof GenreSlugRoute
  '/works/$workId': typeof WorksWorkIdRoute
  '/write/new': typeof WriteNewRoute
  '/write/': typeof WriteIndexRoute
  '/read/$workId/$chapterId': typeof ReadWorkIdChapterIdRoute
  '/write/analytics/$workId': typeof WriteAnalyticsWorkIdRoute
  '/write/manage/$workId': typeof WriteManageWorkIdRoute
  '/write/editor/$workId/$chapterId': typeof WriteEditorWorkIdChapterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design-system'
    | '/discover'
    | '/following'
    | '/library'
    | '/notifications'
    | '/profile'
    | '/search'
    | '/secret-adminpanel'
    | '/settings'
    | '/author/$authorId'
    | '/category/$slug'
    | '/genre/$slug'
    | '/works/$workId'
    | '/write/new'
    | '/write/'
    | '/read/$workId/$chapterId'
    | '/write/analytics/$workId'
    | '/write/manage/$workId'
    | '/write/editor/$workId/$chapterId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design-system'
    | '/discover'
    | '/following'
    | '/library'
    | '/notifications'
    | '/profile'
    | '/search'
    | '/secret-adminpanel'
    | '/settings'
    | '/author/$authorId'
    | '/category/$slug'
    | '/genre/$slug'
    | '/works/$workId'
    | '/write/new'
    | '/write'
    | '/read/$workId/$chapterId'
    | '/write/analytics/$workId'
    | '/write/manage/$workId'
    | '/write/editor/$workId/$chapterId'
  id:
    | '__root__'
    | '/'
    | '/design-system'
    | '/discover'
    | '/following'
    | '/library'
    | '/notifications'
    | '/profile'
    | '/search'
    | '/secret-adminpanel'
    | '/settings'
    | '/author/$authorId'
    | '/category/$slug'
    | '/genre/$slug'
    | '/works/$workId'
    | '/write/new'
    | '/write/'
    | '/read/$workId/$chapterId'
    | '/write/analytics/$workId'
    | '/write/manage/$workId'
    | '/write/editor/$workId/$chapterId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignSystemRoute: typeof DesignSystemRoute
  DiscoverRoute: typeof DiscoverRoute
  FollowingRoute: typeof FollowingRoute
  LibraryRoute: typeof LibraryRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  SecretAdminpanelRoute: typeof SecretAdminpanelRoute
  SettingsRoute: typeof SettingsRoute
  AuthorAuthorIdRoute: typeof AuthorAuthorIdRoute
  CategorySlugRoute: typeof CategorySlugRoute
  GenreSlugRoute: typeof GenreSlugRoute
  WorksWorkIdRoute: typeof WorksWorkIdRoute
  WriteNewRoute: typeof WriteNewRoute
  WriteIndexRoute: typeof WriteIndexRoute
  ReadWorkIdChapterIdRoute: typeof ReadWorkIdChapterIdRoute
  WriteAnalyticsWorkIdRoute: typeof WriteAnalyticsWorkIdRoute
  WriteManageWorkIdRoute: typeof WriteManageWorkIdRoute
  WriteEditorWorkIdChapterIdRoute: typeof WriteEditorWorkIdChapterIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/following': {
      id: '/following'
      path: '/following'
      fullPath: '/following'
      preLoaderRoute: typeof FollowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secret-adminpanel': {
      id: '/secret-adminpanel'
      path: '/secret-adminpanel'
      fullPath: '/secret-adminpanel'
      preLoaderRoute: typeof SecretAdminpanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author/$authorId': {
      id: '/author/$authorId'
      path: '/author/$authorId'
      fullPath: '/author/$authorId'
      preLoaderRoute: typeof AuthorAuthorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genre/$slug': {
      id: '/genre/$slug'
      path: '/genre/$slug'
      fullPath: '/genre/$slug'
      preLoaderRoute: typeof GenreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/$workId': {
      id: '/works/$workId'
      path: '/works/$workId'
      fullPath: '/works/$workId'
      preLoaderRoute: typeof WorksWorkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/write/': {
      id: '/write/'
      path: '/write'
      fullPath: '/write/'
      preLoaderRoute: typeof WriteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/write/new': {
      id: '/write/new'
      path: '/write/new'
      fullPath: '/write/new'
      preLoaderRoute: typeof WriteNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$workId/$chapterId': {
      id: '/read/$workId/$chapterId'
      path: '/read/$workId/$chapterId'
      fullPath: '/read/$workId/$chapterId'
      preLoaderRoute: typeof ReadWorkIdChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/write/analytics/$workId': {
      id: '/write/analytics/$workId'
      path: '/write/analytics/$workId'
      fullPath: '/write/analytics/$workId'
      preLoaderRoute: typeof WriteAnalyticsWorkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/write/manage/$workId': {
      id: '/write/manage/$workId'
      path: '/write/manage/$workId'
      fullPath: '/write/manage/$workId'
      preLoaderRoute: typeof WriteManageWorkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/write/editor/$workId/$chapterId': {
      id: '/write/editor/$workId/$chapterId'
      path: '/write/editor/$workId/$chapterId'
      fullPath: '/write/editor/$workId/$chapterId'
      preLoaderRoute: typeof WriteEditorWorkIdChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignSystemRoute: DesignSystemRoute,
  DiscoverRoute: DiscoverRoute,
  FollowingRoute: FollowingRoute,
  LibraryRoute: LibraryRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  SecretAdminpanelRoute: SecretAdminpanelRoute,
  SettingsRoute: SettingsRoute,
  AuthorAuthorIdRoute: AuthorAuthorIdRoute,
  CategorySlugRoute: CategorySlugRoute,
  GenreSlugRoute: GenreSlugRoute,
  WorksWorkIdRoute: WorksWorkIdRoute,
  WriteNewRoute: WriteNewRoute,
  WriteIndexRoute: WriteIndexRoute,
  ReadWorkIdChapterIdRoute: ReadWorkIdChapterIdRoute,
  WriteAnalyticsWorkIdRoute: WriteAnalyticsWorkIdRoute,
  WriteManageWorkIdRoute: WriteManageWorkIdRoute,
  WriteEditorWorkIdChapterIdRoute: WriteEditorWorkIdChapterIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
